# Generated by Django 4.2.1 on 2023-07-17 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.batch')),
                ('Room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.rooms')),
                ('Timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.timings')),
                ('Trainer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.trainer')),
            ],
            options={
                'verbose_name_plural': 'Room Allocation',
            },
        ),
    ]
